"""initial_schema

Revision ID: dd9b7af5d8b3
Revises: 
Create Date: 2026-05-20 09:15:45.328761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd9b7af5d8b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins'))
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('drivers',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('ci', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('license_category', sa.String(length=20), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers'))
    )
    op.create_index(op.f('ix_drivers_ci'), 'drivers', ['ci'], unique=True)
    op.create_index(op.f('ix_drivers_email'), 'drivers', ['email'], unique=True)
    op.create_table('file_imports',
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.Column('error_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_imports'))
    )
    op.create_table('lines',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('average_speed_kmh', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lines'))
    )
    op.create_index(op.f('ix_lines_code'), 'lines', ['code'], unique=True)
    op.create_table('offline_packages',
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.BIGINT(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offline_packages')),
    sa.UniqueConstraint('version', name=op.f('uq_offline_packages_version'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_settings_key'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('names', sa.String(length=120), nullable=True),
    sa.Column('last_names', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('buses',
    sa.Column('plate', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('seats_count', sa.Integer(), nullable=False),
    sa.Column('internal_number', sa.String(length=50), nullable=False),
    sa.Column('current_line_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_line_id'], ['lines.id'], name=op.f('fk_buses_current_line_id_lines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buses'))
    )
    op.create_index(op.f('ix_buses_current_line_id'), 'buses', ['current_line_id'], unique=False)
    op.create_index(op.f('ix_buses_plate'), 'buses', ['plate'], unique=True)
    op.create_table('favorite_places',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorite_places_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorite_places'))
    )
    op.create_index(op.f('ix_favorite_places_user_id'), 'favorite_places', ['user_id'], unique=False)
    op.create_table('line_variants',
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], name=op.f('fk_line_variants_line_id_lines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_line_variants'))
    )
    op.create_index(op.f('ix_line_variants_line_id'), 'line_variants', ['line_id'], unique=False)
    op.create_table('user_route_history',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('origin', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('destination', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=False),
    sa.Column('walking_distance_m', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transfers_count', sa.Integer(), nullable=False),
    sa.Column('route_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_route_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_route_history'))
    )
    op.create_index(op.f('ix_user_route_history_user_id'), 'user_route_history', ['user_id'], unique=False)
    op.create_table('bus_driver_assignments',
    sa.Column('bus_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], name=op.f('fk_bus_driver_assignments_bus_id_buses')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_bus_driver_assignments_driver_id_drivers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bus_driver_assignments'))
    )
    op.create_index(op.f('ix_bus_driver_assignments_bus_id'), 'bus_driver_assignments', ['bus_id'], unique=False)
    op.create_index(op.f('ix_bus_driver_assignments_driver_id'), 'bus_driver_assignments', ['driver_id'], unique=False)
    op.create_table('routes',
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('total_distance_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], name=op.f('fk_routes_line_id_lines')),
    sa.ForeignKeyConstraint(['variant_id'], ['line_variants.id'], name=op.f('fk_routes_variant_id_line_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes'))
    )
    op.create_index(op.f('ix_routes_line_id'), 'routes', ['line_id'], unique=False)
    op.create_index(op.f('ix_routes_variant_id'), 'routes', ['variant_id'], unique=False)
    op.create_table('active_trips',
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('bus_id', sa.UUID(), nullable=False),
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], name=op.f('fk_active_trips_bus_id_buses')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_active_trips_driver_id_drivers')),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], name=op.f('fk_active_trips_line_id_lines')),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_active_trips_route_id_routes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_active_trips'))
    )
    op.create_index(op.f('ix_active_trips_bus_id'), 'active_trips', ['bus_id'], unique=False)
    op.create_index(op.f('ix_active_trips_driver_id'), 'active_trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_active_trips_line_id'), 'active_trips', ['line_id'], unique=False)
    op.create_table('route_points',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_points_route_id_routes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_points')),
    sa.UniqueConstraint('route_id', 'sequence', name='uq_route_points_route_sequence')
    )
    op.create_index(op.f('ix_route_points_route_id'), 'route_points', ['route_id'], unique=False)
    op.create_table('stops',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_stops_route_id_routes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stops'))
    )
    op.create_index(op.f('ix_stops_route_id'), 'stops', ['route_id'], unique=False)
    op.create_table('tracking_locations',
    sa.Column('active_trip_id', sa.UUID(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('speed', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['active_trip_id'], ['active_trips.id'], name=op.f('fk_tracking_locations_active_trip_id_active_trips')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracking_locations'))
    )
    op.create_index(op.f('ix_tracking_locations_active_trip_id'), 'tracking_locations', ['active_trip_id'], unique=False)
    op.create_index('ix_tracking_locations_trip_recorded', 'tracking_locations', ['active_trip_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tracking_locations_trip_recorded', table_name='tracking_locations')
    op.drop_index(op.f('ix_tracking_locations_active_trip_id'), table_name='tracking_locations')
    op.drop_table('tracking_locations')
    op.drop_index(op.f('ix_stops_route_id'), table_name='stops')
    op.drop_table('stops')
    op.drop_index(op.f('ix_route_points_route_id'), table_name='route_points')
    op.drop_table('route_points')
    op.drop_index(op.f('ix_active_trips_line_id'), table_name='active_trips')
    op.drop_index(op.f('ix_active_trips_driver_id'), table_name='active_trips')
    op.drop_index(op.f('ix_active_trips_bus_id'), table_name='active_trips')
    op.drop_table('active_trips')
    op.drop_index(op.f('ix_routes_variant_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_line_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_bus_driver_assignments_driver_id'), table_name='bus_driver_assignments')
    op.drop_index(op.f('ix_bus_driver_assignments_bus_id'), table_name='bus_driver_assignments')
    op.drop_table('bus_driver_assignments')
    op.drop_index(op.f('ix_user_route_history_user_id'), table_name='user_route_history')
    op.drop_table('user_route_history')
    op.drop_index(op.f('ix_line_variants_line_id'), table_name='line_variants')
    op.drop_table('line_variants')
    op.drop_index(op.f('ix_favorite_places_user_id'), table_name='favorite_places')
    op.drop_table('favorite_places')
    op.drop_index(op.f('ix_buses_plate'), table_name='buses')
    op.drop_index(op.f('ix_buses_current_line_id'), table_name='buses')
    op.drop_table('buses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('offline_packages')
    op.drop_index(op.f('ix_lines_code'), table_name='lines')
    op.drop_table('lines')
    op.drop_table('file_imports')
    op.drop_index(op.f('ix_drivers_email'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_ci'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
